# Generated by Django 3.2.13 on 2022-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220810_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='drawing',
        ),
        migrations.RemoveField(
            model_name='reportmsn0000',
            name='drawing',
        ),
        migrations.AddField(
            model_name='item',
            name='bom',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Ebom0000'),
        ),
    ]
