# Generated by Django 3.2.13 on 2022-10-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_group_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='item',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttask', to='posts.item'),
        ),
    ]
