# Generated by Django 3.2.13 on 2022-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_tasks_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='posts/', verbose_name='Picture'),
        ),
    ]
