# Generated by Django 3.2.13 on 2022-10-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_remove_tasks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='posts/', verbose_name='Picture'),
        ),
    ]
