# Generated by Django 3.2.13 on 2023-03-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_alter_profile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_usd', models.FloatField(blank=True, default=0, null=True)),
                ('currency_aed', models.FloatField(blank=True, default=0, null=True)),
                ('currency_eur', models.FloatField(blank=True, default=0, null=True)),
                ('currency_cnr', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
