# Generated by Django 3.2.13 on 2023-03-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_aed',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_cnr',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_eur',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_usd',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
