# Generated by Django 3.2.13 on 2023-02-23 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0034_alter_profile_department'),
        ('nonconformance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='com', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nn_name', models.CharField(max_length=20)),
                ('nn_status', models.CharField(choices=[('SEND BACK', 'SENT BACK'), ('INITIATED', 'INITIATED'), ('OPEN', 'OPENED'), ('CLOSED', 'CLOSED')], max_length=20)),
                ('reason', models.CharField(choices=[('Airworthiness', 'Airworthiness'), ('Functional improvement', 'Functional improvement'), ('Customer request', 'Customer request'), ('Procurement difficulties', 'Procurement difficulties'), ('Cost reduction', 'Cost reduction'), ('Production process improvement', 'Production process improvement'), ('Other', 'Other')], max_length=100)),
                ('description_of_change', models.TextField()),
                ('description_of_change_image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Picture')),
                ('solutions', models.TextField()),
                ('applicant_date', models.DateField(auto_now_add=True)),
                ('doa_decision', models.TextField(blank=True, null=True)),
                ('request_evaluation', models.CharField(blank=True, choices=[('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], max_length=100, null=True)),
                ('annex', models.FileField(blank=True, upload_to='posts/')),
                ('applicability', models.ManyToManyField(to='posts.Prototype')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app', to='posts.profile')),
                ('cdo_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='c_d_o', to=settings.AUTH_USER_MODEL)),
                ('impact_areas_proposal', models.ManyToManyField(blank=True, null=True, related_name='i_a_p', to='posts.Profile')),
                ('oaw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='o_a_w', to='posts.profile')),
                ('part_number', models.ManyToManyField(blank=True, null=True, to='posts.Ebom0000')),
            ],
        ),
        migrations.CreateModel(
            name='PRTProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpt_process_status', models.CharField(choices=[('DISPATCHED', 'DISPATCHED'), ('SENT FOR DE REVIEW', 'SENT FOR DE REVIEW'), ('INWORK BY DE', 'INWORK BY DE'), ('SENT FOR OAW REVIEW', 'SENT FOR OAW REVIEW'), ('CLOSURE', 'CLOSURE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpt_name', models.CharField(max_length=20)),
                ('rpt_review_status', models.CharField(blank=True, choices=[('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], max_length=20, null=True)),
                ('rpt_process_status', models.CharField(blank=True, choices=[('DISPATCHED', 'DISPATCHED'), ('SENT FOR DE REVIEW', 'SENT FOR DE REVIEW'), ('INWORK BY DE', 'INWORK BY DE'), ('SENT FOR OAW REVIEW', 'SENT FOR OAW REVIEW'), ('CLOSURE', 'CLOSURE')], max_length=120)),
                ('applicant_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('description_image', models.ImageField(blank=True, upload_to='posts/', verbose_name='Picture')),
                ('review_note', models.TextField(blank=True)),
                ('oaw_date', models.DateField(blank=True)),
                ('do_date_receipt', models.DateField(blank=True)),
                ('do_date', models.DateField(blank=True)),
                ('hoaw_date', models.DateField(blank=True)),
                ('oaw_note', models.TextField(blank=True)),
                ('dcp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dcp', to='nonconformance.dcp')),
                ('dispatched_to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dis', to=settings.AUTH_USER_MODEL)),
                ('do', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='do', to='posts.profile')),
                ('do_receipt', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_r', to='posts.profile')),
                ('hoaw', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoaw', to='posts.profile')),
                ('oaw', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oaw', to='posts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='nnstatus',
            name='nn_status',
            field=models.CharField(choices=[('SEND BACK', 'SENT BACK'), ('INITIATED', 'INITIATED'), ('OPEN', 'OPENED'), ('CLOSED', 'CLOSED')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Nonconformance',
        ),
        migrations.AddField(
            model_name='rpt',
            name='rpt_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpt', to='nonconformance.nnstatus'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='com', to='nonconformance.dcp'),
        ),
    ]
