# Generated by Django 3.2.13 on 2023-02-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_auto_20230223_1950'),
        ('nonconformance', '0003_auto_20230223_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnstatus',
            name='nn_status',
            field=models.CharField(choices=[('SEND BACK', 'SENT BACK'), ('RPT CLOSED', 'RPTs CLOSED'), ('RPT DISPATCHED', 'RPTs DISPATCHED'), ('READY FOR RPT', 'READY FOR RPT'), ('INITIATED', 'INITIATED'), ('OPEN', 'OPENED'), ('CLOSED', 'CLOSED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='do_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='do_date_receipt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='hoaw_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='oaw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oaw', to='posts.profile'),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='oaw_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
