# Generated by Django 3.2.13 on 2023-02-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0006_alter_rpt_rpt_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prtreviewstatus',
            old_name='rpt_process_status',
            new_name='rpt_review_status',
        ),
    ]
