# Generated by Django 3.2.13 on 2023-02-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0002_auto_20230223_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRTreviewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpt_process_status', models.CharField(choices=[('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dcp',
            name='nn_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformance.nnstatus'),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='rpt_process_status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nonconformance.prtprocessstatus'),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='rpt_review_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nonconformance.prtreviewstatus'),
        ),
    ]
