# Generated by Django 3.2.13 on 2023-02-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_auto_20230223_1950'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nonconformance', '0004_auto_20230225_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='description_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='dispatched_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='do',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='do', to='posts.profile'),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='do_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_r', to='posts.profile'),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='hoaw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoaw', to='posts.profile'),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='oaw_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpt',
            name='rpt_process_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nonconformance.prtprocessstatus'),
        ),
    ]
