# Generated by Django 3.2.13 on 2023-02-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0009_auto_20230228_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrerason',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
