# Generated by Django 3.2.13 on 2022-08-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.FileField(blank=True, upload_to='posts/', verbose_name='Picture'),
        ),
    ]
