# Generated by Django 3.2.13 on 2022-08-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_item_bom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bom',
        ),
        migrations.AddField(
            model_name='item',
            name='drawing',
            field=models.ManyToManyField(blank=True, null=True, through='posts.ReportMsn0000', to='posts.Ebom0000'),
        ),
        migrations.AddField(
            model_name='reportmsn0000',
            name='drawing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.ebom0000'),
            preserve_default=False,
        ),
    ]
