# Generated by Django 3.2.13 on 2022-08-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220816_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bom_ver',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rout_ver',
            field=models.IntegerField(blank=True),
        ),
    ]
