# Generated by Django 3.2.13 on 2022-08-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_reportmsn0000_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed_date',
            field=models.DateTimeField(null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
