# Generated by Django 3.2.13 on 2023-02-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Picture'),
        ),
    ]
