# Generated by Django 3.2.13 on 2023-02-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0008_auto_20230228_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherrerason',
            name='author',
        ),
        migrations.RemoveField(
            model_name='otherrerason',
            name='date',
        ),
        migrations.RemoveField(
            model_name='otherrerason',
            name='nn',
        ),
        migrations.AlterField(
            model_name='otherrerason',
            name='dcp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
