# Generated by Django 3.2.13 on 2023-03-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0011_otherrerason_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherrerason',
            name='slug',
        ),
    ]
