# Generated by Django 3.2.14 on 2023-04-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_auto_20230308_2057'),
        ('nonconformance', '0012_remove_otherrerason_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdc_name', models.CharField(max_length=25)),
                ('tdc_rev', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('incorporate', models.CharField(blank=True, choices=[('INCORPORATED', 'INCORPORATED'), ('NOTINCORPORATED', 'NOTINCORPORATED')], max_length=50, null=True)),
                ('doc_number_to_change', models.CharField(blank=True, max_length=50, null=True)),
                ('description_of_change', models.TextField(blank=True, null=True)),
                ('reason_of_change', models.TextField(blank=True, null=True)),
                ('organinizational', models.BooleanField(default=False)),
                ('organinizational_text', models.CharField(blank=True, max_length=50, null=True)),
                ('technical_not_substantial', models.BooleanField(default=True)),
                ('minor', models.BooleanField(default=False)),
                ('major', models.BooleanField(default=False)),
                ('fcd_mmel', models.CharField(blank=True, choices=[('MINOR', 'MINOR'), ('MAJOR', 'MAJOR')], max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_oaw', models.DateField(blank=True, null=True)),
                ('date_hoaw', models.DateField(blank=True, null=True)),
                ('hdo_date', models.DateField(blank=True, null=True)),
                ('compliance', models.TextField(blank=True, null=True)),
                ('HDO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tdc', to='posts.profile')),
                ('approved_hoaw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_hoaw', to='posts.profile')),
                ('dcp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tds_rpt', to='nonconformance.dcp')),
                ('prepared_oaw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_pre_oaw', to='posts.profile')),
            ],
        ),
    ]
