# Generated by Django 3.2.14 on 2023-04-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0013_tdc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocNumberChanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=50)),
                ('rev', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('previous_assy', models.CharField(blank=True, max_length=50)),
                ('prev_rev', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DocNumberToChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=50)),
                ('rev', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('previous_assy', models.CharField(blank=True, max_length=50)),
                ('prev_rev', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='tdc',
            name='doc_number_changed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tdc',
            name='incorporate',
            field=models.BooleanField(default=False),
        ),
    ]
