# Generated by Django 3.2.14 on 2023-04-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_auto_20230308_2057'),
        ('nonconformance', '0014_auto_20230417_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orf_name', models.CharField(max_length=25)),
                ('orf_rev', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('orf_evaluation_status', models.CharField(blank=True, choices=[('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('HDO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hoaw_orf', to='posts.profile')),
                ('dcp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dcp_orf', to='nonconformance.dcp')),
                ('nn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nn_orf', to='nonconformance.nn')),
                ('prepared_oaw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oaw_orf', to='posts.profile')),
            ],
        ),
    ]
