# Generated by Django 3.2.14 on 2023-04-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0015_orf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orf',
            name='orf_process_status',
            field=models.CharField(blank=True, choices=[('PREPARED', 'PREPARED'), ('APPROVED', 'APPROVED')], max_length=100, null=True),
        ),
    ]
