# Generated by Django 3.2.14 on 2023-04-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0016_orf_orf_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnstatus',
            name='nn_status',
            field=models.CharField(choices=[('SEND BACK', 'SENT BACK'), ('INITIATED', 'INITIATED'), ('READY FOR RPT', 'READY FOR RPT'), ('RPT DISPATCHED', 'RPTs DISPATCHED'), ('RPT CLOSED', 'RPTs CLOSED'), ('ORF PREPARED', 'ORF PREPARED'), ('ORF APPROVED', 'ORF APPROVED'), ('TDC PREPARED', 'TDC PREPARED'), ('TDC APPROVED', 'TDC APPROVED'), ('OPEN', 'OPENED'), ('CLOSED', 'CLOSED')], max_length=20),
        ),
    ]
