# Generated by Django 3.2.14 on 2023-04-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0018_tdc_tcp_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcp',
            name='oaw_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcp',
            name='request_evaluation',
            field=models.CharField(choices=[('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], max_length=100, null=True),
        ),
    ]
