# Generated by Django 3.2.14 on 2023-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0019_auto_20230420_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnstatus',
            name='nn_status',
            field=models.CharField(choices=[('SEND BACK', 'SENT BACK'), ('INITIATED', 'INITIATED'), ('READY FOR RPT EVALUATION', 'READY FOR RPT DO EVALUATION'), ('RPT DISPATCHED', 'RPTs DISPATCHED'), ('RPT DO EVALUATED', 'RPT DO EVALUATED'), ('RPT CLOSED', 'RPTs CLOSED'), ('ORF PREPARED', 'ORF PREPARED'), ('ORF APPROVED', 'ORF APPROVED'), ('TDC PREPARED', 'TDC PREPARED'), ('TDC APPROVED', 'TDC APPROVED'), ('OPEN', 'OPENED'), ('CLOSED', 'CLOSED')], max_length=30),
        ),
    ]
