# Generated by Django 3.2.14 on 2023-04-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0020_alter_nnstatus_nn_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnstatus',
            name='nn_status',
            field=models.CharField(choices=[('SEND BACK', 'SENT BACK'), ('INITIATED', 'INITIATED'), ('READY FOR RPT DO EVALUATION', 'READY FOR RPT DO EVALUATION'), ('RPT DISPATCHED', 'RPTs DISPATCHED'), ('RPT DO EVALUATED', 'RPT DO EVALUATED'), ('RPT CLOSED', 'RPTs CLOSED'), ('ORF PREPARED', 'ORF PREPARED'), ('ORF APPROVED', 'ORF APPROVED'), ('TDC PREPARED', 'TDC PREPARED'), ('TDC APPROVED', 'TDC APPROVED'), ('OPEN', 'OPENED'), ('CLOSED', 'CLOSED'), ('READY FOR DIAP', 'READY FOR DIAP')], max_length=30),
        ),
    ]
