# Generated by Django 3.2.13 on 2022-08-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220810_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='maturity_state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
