# Generated by Django 3.2.13 on 2022-08-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220816_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebom0000',
            name='revision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ebom0000',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
