# Generated by Django 3.2.13 on 2022-08-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20220817_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='planned_time',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateField(null=True, verbose_name='completed_date'),
        ),
    ]
