# Generated by Django 3.2.13 on 2023-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Signature'),
        ),
    ]
